export interface PreambleCtx {
  date: string
  units: 'mm' | 'in'
  unitCmd: 'G21' | 'G20'
  bitType: string
  diameter: number
  spindleRpm: number
  safeHeight: number
  materialThickness: number
  fmt: (n: number) => string
}

export interface PostProcessorDef {
  id: string
  name: string
  description: string
  fileExtension: string
  defaultLineNumbers: boolean
  /** First character of a comment line — used to skip line-numbering */
  commentChar: ';' | '('
  comment: (text: string) => string
  /** Emitted verbatim as the very first line (e.g. Mach3 '%') — empty string = omit */
  programStart: string
  /** Emitted verbatim as the very last line */
  programEnd: string
  /** Full setup block: header comments, modal init, spindle on, safe-Z move */
  preamble: (ctx: PreambleCtx) => string[]
  /** Commands after the final safe-Z return: spindle off, program end word */
  postamble: string[]
}

// ─────────────────────────────────────────────────────────────────────────────

const SEP = '─'.repeat(65)

export const POST_PROCESSORS: PostProcessorDef[] = [
  // ── FluidNC / GRBL ─────────────────────────────────────────────────────────
  {
    id: 'fluidnc',
    name: 'FluidNC / GRBL',
    description: 'FluidNC and standard GRBL-based controllers',
    fileExtension: '.gcode',
    defaultLineNumbers: false,
    commentChar: ';',
    comment: (t) => `; ${t}`,
    programStart: '',
    programEnd: '',
    preamble: (ctx) => [
      `; Generated by Carver — ${ctx.date}`,
      `; Tool: ${ctx.bitType}  dia ${ctx.fmt(ctx.diameter)}${ctx.units}  |  Spindle: ${ctx.spindleRpm} rpm`,
      `; Material: ${ctx.fmt(ctx.materialThickness)}${ctx.units} thick  |  Safe Z: ${ctx.fmt(ctx.safeHeight)}${ctx.units}`,
      `; ${SEP}`,
      'G90 G17',
      ctx.unitCmd,
      `M3 S${ctx.spindleRpm}`,
      `G0 Z${ctx.fmt(ctx.safeHeight)}`,
    ],
    postamble: ['M5', 'M30'],
  },

  // ── LinuxCNC (RS274/NGC) ────────────────────────────────────────────────────
  {
    id: 'linuxcnc',
    name: 'LinuxCNC (RS274/NGC)',
    description: 'LinuxCNC / EMC2 with .ngc file format',
    fileExtension: '.ngc',
    defaultLineNumbers: false,
    commentChar: '(',
    comment: (t) => `(${t})`,
    programStart: '',
    programEnd: '',
    preamble: (ctx) => [
      `(Generated by Carver — ${ctx.date})`,
      `(Tool: ${ctx.bitType}  dia ${ctx.fmt(ctx.diameter)}${ctx.units})`,
      `(Spindle: ${ctx.spindleRpm} rpm  |  Safe Z: ${ctx.fmt(ctx.safeHeight)}${ctx.units})`,
      ctx.unitCmd,
      'G90 G40 G49',
      'G17',
      'G54',
      `M3 S${ctx.spindleRpm}`,
      `G0 Z${ctx.fmt(ctx.safeHeight)}`,
    ],
    postamble: ['M5', 'M2'],
  },

  // ── Mach3 / Mach4 ─────────────────────────────────────────────────────────
  {
    id: 'mach3',
    name: 'Mach3 / Mach4',
    description: 'Mach3 and Mach4 controllers — uses % delimiters and line numbers',
    fileExtension: '.tap',
    defaultLineNumbers: true,
    commentChar: '(',
    comment: (t) => `(${t})`,
    programStart: '%',
    programEnd: '%',
    preamble: (ctx) => [
      `(Generated by Carver — ${ctx.date})`,
      `(Tool: ${ctx.bitType}  dia ${ctx.fmt(ctx.diameter)}${ctx.units})`,
      `(Spindle: ${ctx.spindleRpm} rpm  |  Safe Z: ${ctx.fmt(ctx.safeHeight)}${ctx.units})`,
      ctx.unitCmd,
      'G90',
      `M3 S${ctx.spindleRpm}`,
      `G0 Z${ctx.fmt(ctx.safeHeight)}`,
    ],
    postamble: ['M5', 'M30'],
  },

  // ── Marlin (laser) ─────────────────────────────────────────────────────────
  {
    id: 'marlin-laser',
    name: 'Marlin (laser)',
    description: 'Marlin firmware in laser mode — S value controls laser power',
    fileExtension: '.gcode',
    defaultLineNumbers: false,
    commentChar: ';',
    comment: (t) => `; ${t}`,
    programStart: '',
    programEnd: '',
    preamble: (ctx) => [
      `; Generated by Carver — ${ctx.date}`,
      `; Laser power (S): ${ctx.spindleRpm}  |  Safe Z: ${ctx.fmt(ctx.safeHeight)}${ctx.units}`,
      `; ${SEP}`,
      ctx.unitCmd,
      'G90',
      'M5',                               // ensure laser off at start
      `G0 Z${ctx.fmt(ctx.safeHeight)}`,
      `M3 S${ctx.spindleRpm}`,            // laser on at job start
    ],
    postamble: ['M5', 'M30'],
  },
]

export function getPostProcessor(id: string): PostProcessorDef {
  return POST_PROCESSORS.find(p => p.id === id) ?? POST_PROCESSORS[0]
}
