import type { Toolpath, Move } from '@/types'

export interface GcodeOptions {
  units: 'mm' | 'in'
  bedWidth: number
  bedHeight: number
  originPosition: 'front-left' | 'center'
  spindleRpm: number
  safeHeight: number
  stockSurfaceZ: number
  toolDiameter: number
  bitType: string
  materialThickness: number
  precision: number     // decimal places 1–6
  lineNumbers: boolean
}

export interface GcodeResult {
  gcode: string
  lineCount: number
  byteSize: number
}

export function serializeGcode(toolpaths: Toolpath[], opts: GcodeOptions): GcodeResult {
  const p = Math.max(1, Math.min(6, opts.precision))
  const lines: string[] = []
  let lineNum = 10

  // Comments never get line numbers
  const emit = (s: string) => {
    if (s === '' || s.startsWith(';')) {
      lines.push(s)
    } else if (opts.lineNumbers) {
      lines.push(`N${lineNum} ${s}`)
      lineNum += 10
    } else {
      lines.push(s)
    }
  }

  // ── Coordinate transforms ─────────────────────────────────────────────────
  // Canvas: X right, Y down (top = 0)
  // G-code: X right, Y up (front of machine = Y 0)
  const tx = (x: number): number =>
    opts.originPosition === 'center' ? x - opts.bedWidth / 2 : x

  const ty = (y: number): number => {
    const flipped = opts.bedHeight - y
    return opts.originPosition === 'center' ? flipped - opts.bedHeight / 2 : flipped
  }

  const fmt = (n: number) => n.toFixed(p)

  // ── Modal state (stored as formatted strings to avoid float comparison bugs) ─
  let cx: string | null = null
  let cy: string | null = null
  let cz: string | null = null
  let cf: string | null = null

  const emitMove = (m: Move) => {
    const fmx = fmt(tx(m.x))
    const fmy = fmt(ty(m.y))
    const fmz = fmt(m.z)
    const cmd = m.rapid ? 'G0' : 'G1'
    const parts: string[] = [cmd]

    if (fmx !== cx) { parts.push(`X${fmx}`); cx = fmx }
    if (fmy !== cy) { parts.push(`Y${fmy}`); cy = fmy }
    if (fmz !== cz) { parts.push(`Z${fmz}`); cz = fmz }

    if (!m.rapid && m.feed != null) {
      const ff = String(Math.round(m.feed))
      if (ff !== cf) { parts.push(`F${ff}`); cf = ff }
    }

    if (parts.length > 1) emit(parts.join(' '))
  }

  // ── Preamble ──────────────────────────────────────────────────────────────
  const date = new Date().toISOString().slice(0, 10)
  const u = opts.units
  emit(`; Generated by Carver — ${date}`)
  emit(`; Tool: ${opts.bitType}  dia ${opts.toolDiameter.toFixed(2)}${u}  |  Spindle: ${opts.spindleRpm} rpm`)
  emit(`; Material: ${opts.materialThickness}${u} thick  |  Safe Z: ${opts.safeHeight}${u}`)
  emit('; -----------------------------------------------------------------')
  emit('G90 G17')                                // absolute coords, XY plane
  emit(opts.units === 'mm' ? 'G21' : 'G20')     // unit mode
  emit(`M3 S${opts.spindleRpm}`)                 // spindle on
  emit(`G0 Z${fmt(opts.safeHeight)}`)            // move to safe height
  cz = fmt(opts.safeHeight)                      // prime modal Z

  // ── Toolpaths ─────────────────────────────────────────────────────────────
  toolpaths.forEach((tp, i) => {
    emit('')
    emit(`; --- ${i + 1}/${toolpaths.length}: ${tp.operation} (${tp.moves.length} moves) ---`)
    for (const m of tp.moves) emitMove(m)
  })

  // ── Postamble ─────────────────────────────────────────────────────────────
  emit('')
  if (cz !== fmt(opts.safeHeight)) emit(`G0 Z${fmt(opts.safeHeight)}`)
  emit('M5')   // spindle off
  emit('M30')  // program end

  const gcode = lines.join('\n')
  return {
    gcode,
    lineCount: lines.length,
    byteSize: new TextEncoder().encode(gcode).length,
  }
}
